---
title: "Master Thesis Code"
author: "Nina van Gerwen (1860852)"
date: "2022-10-28"
output: html_document
---

## Functions for IRF calculations

These are necessary in data generation as we will vary the data generating model.

```{r}
source("Functions/model-calculations.R")
source("Functions/start.values.R")
source("Functions/multigroup-data-gen.R")
source("Functions/multigroup-lr-test-calculation.R")
```

## Empirical alpha analysis

```{r Final first run}
library(ltm)
library(dplyr)
library(mirt)
library(tidyr)
## This is for empirical alpha estimation
test_length <- as.factor(c(5, 10, 20))
sample_size <- as.factor(c(200, 300, 500, 1000, 1500))
n_groups <- as.factor(c(2, 3, 4))

n_sim <- 300

## We vary three factors, and for the simulation study, we 
## cross-examine them through a nested for loop

alpha_results_two <- data.frame(test_length = NA, sample_size = NA, G = NA, MG.LR = NA)

set.seed(1248)

for(a in levels(test_length)){

  for(b in levels(sample_size)){
    
    for(d in levels(n_groups)){
      
      prop_1 <- rep(NA, n_sim)
      
      temp_k <- as.numeric(as.character(a))
      temp_g <- as.numeric(as.character(d))
      temp_n <- round(as.numeric(as.character(b))/temp_g)
      
      start.vals <- start.values(temp_k)
      
        for(i in 1:n_sim){
        ## Then, for every condition, generate data according to the
        ## current condition

          temp_data <- multigroup.data.gen(n = temp_n, k = temp_k, g = temp_g, 
                                           method = "param", model = "2PL")
            
          temp_model <- ltm(temp_data[ , 1:temp_k] ~ z1, IRT.param = TRUE)
          
          l_0 <- temp_model$log.Lik
        
          p_value_1 <- 1 - pchisq(q = MG.LR.test(l_0 = l_0, data = temp_data, g = temp_g, 
                                                 k = temp_k, start.val = start.vals), 
                              df = (temp_g - 1) * 2 * temp_k)
 
          prop_1[i] <- ifelse(p_value_1 < .05, 1, 0)

        }
      
        alpha_results_two <- rbind(alpha_results_two, c(a, b, d, mean(prop_1)))
      }
      

  }
  
}


alpha_results_two <- alpha_results_two %>% 
  pivot_wider(., names_from = G, values_from = MG.LR) %>%
  .[-1, -3]

rownames(alpha_results_two) <- NULL
colnames(alpha_results_two) <- c("test_length", "sample_size", "LR2", "LR3", "LR4")
  
alpha_results_two

## -----------------------------------------------------------------------------

theta_alpha <- data.frame(test_length = NA, sample_size = NA, G = NA, MG.LR = NA)

set.seed(1248)

for(a in levels(test_length)){

  for(b in levels(sample_size)){
    
    for(d in levels(n_groups)){
      
      prop_1 <- rep(NA, n_sim)
      
      temp_n <- as.numeric(as.character(b))
      temp_k <- as.numeric(as.character(a))
      temp_g <- as.numeric(as.character(d))
      
      start.vals <- start.values(temp_k)
      
        for(i in 1:n_sim){
        ## Then, for every condition, generate data according to the
        ## current condition

          temp_data <- multigroup.data.gen(n = temp_n, k = temp_k, g = temp_g, 
                                           method = "theta", model = "2PL")
            
          temp_model <- ltm(temp_data[ , 1:temp_k] ~ z1, IRT.param = TRUE)
          
          l_0 <- temp_model$log.Lik
        
          p_value_1 <- 1 - pchisq(q = MG.LR.test(l_0 = l_0, data = temp_data, g = temp_g, 
                                                 k = temp_k, start.val = start.vals), 
                              df = (temp_g - 1) * 2 * temp_k)
 
          prop_1[i] <- ifelse(p_value_1 < .05, 1, 0)

        }
      
        theta_alpha <- rbind(theta_alpha, c(a, b, d, mean(prop_1)))
      }
      

  }
  
}


theta_alpha <- theta_alpha %>%
  pivot_wider(., names_from = G, values_from = MG.LR) %>%
  .[-1, -3]
  
rownames(theta_alpha) <- NULL
colnames(theta_alpha) <- c("test_length", "sample_size", "LR2", "LR3", "LR4")
theta_alpha
```


## Power analysis

```{r Final second run}
library(ltm)
library(dplyr)
library(mirt)
## This is for empirical alpha estimation
test_length <- as.factor(c(5, 10, 20))
sample_size <- as.factor(c(200, 300, 500, 1000, 1500))
n_groups <- as.factor(c(2, 3, 4))

n_sim <- 300

## We vary three factors, and for the simulation study, we 
## cross-examine them through a nested for loop

power_results_two <- data.frame(test_length = NA, sample_size = NA, G = NA, MG.LR = NA)

set.seed(1248)

for(a in levels(test_length)){

  for(b in levels(sample_size)){
    
    for(d in levels(n_groups)){
      
      prop_1 <- rep(NA, n_sim)
      
      temp_n <- as.numeric(as.character(b))
      temp_k <- as.numeric(as.character(a))
      temp_g <- as.numeric(as.character(d))
      
      start.vals <- start.values(temp_k)
      
        for(i in 1:n_sim){
        ## Then, for every condition, generate data according to the
        ## current condition

          temp_data <- multigroup.data.gen(n = temp_n, k = temp_k, g = temp_g, 
                                           method = "param", model = "3PL")
            
          temp_model <- ltm(temp_data[ , 1:temp_k] ~ z1, IRT.param = TRUE)
          
          l_0 <- temp_model$log.Lik
        
          p_value_1 <- 1 - pchisq(q = MG.LR.test(l_0 = l_0, data = temp_data, g = temp_g, 
                                                 k = temp_k, start.val = start.vals), 
                              df = (temp_g - 1) * 2 * temp_k)
 
          prop_1[i] <- ifelse(p_value_1 < .05, 1, 0)

        }
      
        power_results_two <- rbind(power_results_two, c(a, b, d, mean(prop_1)))
      }
      

  }
  
}

power_results_two <- power_results_two %>%
  pivot_wider(., names_from = G, values_from = MG.LR) %>%
  .[-1, -3]

rownames(power_results_two) <- NULL
colnames(power_results_two) <- c("test_length", "sample_size", "LR2", "LR3", "LR4")

power_results_two
```

## Power with thetas

```{r Final second run}
library(ltm)
library(dplyr)
library(mirt)
## This is for empirical alpha estimation
test_length <- as.factor(c(5, 10, 20))
sample_size <- as.factor(c(200, 300, 500, 1000, 1500))
n_groups <- as.factor(c(2, 3, 4))

n_sim <- 300

## We vary three factors, and for the simulation study, we 
## cross-examine them through a nested for loop

theta_power <- data.frame(test_length = NA, sample_size = NA, G = NA, MG.LR = NA)

set.seed(1248)

for(a in levels(test_length)){

  for(b in levels(sample_size)){
    
    for(d in levels(n_groups)){
      
      prop_1 <- rep(NA, n_sim)
      
      temp_n <- as.numeric(as.character(b))
      temp_k <- as.numeric(as.character(a))
      temp_g <- as.numeric(as.character(d))
      
      start.vals <- start.values(temp_k)
      
        for(i in 1:n_sim){
        ## Then, for every condition, generate data according to the
        ## current condition

          temp_data <- multigroup.data.gen(n = temp_n, k = temp_k, g = temp_g, 
                                           method = "theta", model = "3PL")
            
          temp_model <- ltm(temp_data[ , 1:temp_k] ~ z1, IRT.param = TRUE)
          
          l_0 <- temp_model$log.Lik
        
          p_value_1 <- 1 - pchisq(q = MG.LR.test(l_0 = l_0, data = temp_data, g = temp_g, 
                                                 k = temp_k, start.val = start.vals), 
                              df = (temp_g - 1) * 2 * temp_k)
 
          prop_1[i] <- ifelse(p_value_1 < .05, 1, 0)

        }
      
        theta_power <- rbind(theta_power, c(a, b, d, mean(prop_1)))
      }
      

  }
  
}


theta_power <- theta_power %>%
  pivot_wider(., names_from = G, values_from = MG.LR) %>%
  .[-1, -3]

rownames(theta_power) <- NULL
colnames(theta_power) <- c("test_length", "sample_size", "LR2", "LR3", "LR4")

theta_power
```


