---
title: "Simulation Study I: Fit indices (TLI, CFI and ICFI)"
author: "Nina van Gerwen (1860852)"
date: "24-03-2023"
output: html_document
---

## 1. Preparation

To run the simulations, we load functions that we created ourselves. For this, we use source() and choose the appropriate files. To 
find out how the functions work exactly, please look at the function files directly.

```{r Function loading}
source("Functions/model-calculations.R")
source("Functions/data-generation.R")
source("Functions/fit-indices calculations.R")
source("Functions/data-aggregation.R")
```

## 2. Null condition

```{r}
## LTM to fit the required models
library(ltm)
## DPLYR for some tidying
library(dplyr)
## MAGRITTR for the pipe
library(magrittr)

## Define the levels of the factors we vary for the simulation study,
test_length <- as.factor(c(5, 10, 20))
sample_size <- as.factor(c(200, 300, 500, 1000, 1500))

## Set the number of replications you want
n_sim <- 300

## Our output will be a data frame with first the conditions, and then the
## results, and we pre-define the data frame here with some NAs
## so that later we can put the results in here
null_results <- data.frame(test_length = NA, sample_size = NA, TLI_M = NA,
                          TLI_SE = NA, CFI_M = NA, CFI_SE = NA, ICFI_M = NA,
                          ICFI_SE = NA)

## Set a seed for reproducibility
set.seed(1248)

## To run the study, we start a nested for loop with the levels of the factors
for(a in levels(test_length)){

  for(b in levels(sample_size)){
      
      ## Then, in every condition, we want to get a vector that can 
      ## contain the fit index values for every replication, so we 
      ## create an empty vector of size
      ## equal to the number of replications for the fit indices
      tli_values <- rep(NA, n_sim)
      cfi_values <- rep(NA, n_sim)
      icfi_values <- rep(NA, n_sim)
      
      ## To improve efficiency, we note the current levels of factors
      ## so that we can refer to this in future function arguments
      temp_n <- as.numeric(as.character(b))
      temp_k <- as.numeric(as.character(a))
      
        ## And now we can start the for loop by which we will get the
        ## fit index value results
        for(j in 1:n_sim){
          
          ## Getting results is done in the following way:
    
          ## First, generating data according to the factors
          temp_data <- data.gen(n = temp_n, k = temp_k, model = "2PL")
                        
          ## Fitting the hypothesized model
          temp_model <- ltm(temp_data ~ z1, IRT.param = TRUE)
          
    ## For efficiency purposes, we note all these values once instead
    ## calculating them for every single fit index 
          
          ## And obtaining the log likelihood
          l_0 <- temp_model$log.Lik
          
          ## For the saturated model, we require an aggregrated version 
          ## of the data, therefore we save this with our own function
          aggr_data <- score.pattern.aggr(temp_data, temp_n)
          
          ## We note the degrees of freedom for the different tested models
          ## through pre-defined functions
          df_base <- df.base(k = temp_k)
          
          df_tested <- df.tested(k = temp_k)
          
          ## And also note the chi-square values of the 
          ## hypothesized model compared to the base and saturated model
          chi_base <- chi.base(agg_data = aggr_data, data = temp_data,
                               n = temp_n, k = temp_k)
          
          chi_tested <- chi.tested(l_0 = l_0, agg_data = aggr_data, n = temp_n)
          
          ## And then calculating the TLI and CFI values through our
          ## specialized functions using the earlier determined df and 
          ## chi-square values
          tli_values[j] <- TLI.Yang(chi_base = chi_base, df_base = df_base, 
                               chi_tested = chi_tested, df_tested = df_tested)
          
          cfi_values[j] <- CFI.Yang(chi_base = chi_base, df_base = df_base, 
                               chi_tested = chi_tested, df_tested = df_tested)
          
          ## And we also calculate the icfi values through a predefined function
          icfi_values[j] <- exp.obs.FI(temp_model, temp_k)
          
        }
      
      ## Then, after the values have been calculated n_sim times, 
      ## we can get their mean and standard deviation and add these
      ## to the result dataframe through rbind()
      null_results <- rbind(null_results, c(a, b, mean(tli_values), sd(tli_values),
                                          mean(cfi_values), sd(cfi_values),
                                          mean(icfi_values), sd(icfi_values)))

  }
  
}

## Now we just have to clean up the dataframe by removing the first row of NAs
null_results <- null_results[-1 ,]
## And resetting the rownames
rownames(null_results) <- NULL

null_results
```


## 3. Miss-specification condition

```{r}
library(ltm)
library(dplyr)
library(magrittr)

test_length <- as.factor(c(5, 10, 20))
sample_size <- as.factor(c(200, 300, 500, 1000, 1500))

n_sim <- 300

miss_results <- data.frame(test_length = NA, sample_size = NA, TLI_M = NA,
                          TLI_SE = NA, CFI_M = NA, CFI_SE = NA, ICFI_M = NA,
                          ICFI_SE = NA)

set.seed(1248)

for(a in levels(test_length)){

  for(b in levels(sample_size)){
      
      tli_values <- rep(NA, n_sim)
      cfi_values <- rep(NA, n_sim)
      icfi_values <- rep(NA, n_sim)
      
      temp_n <- as.numeric(as.character(b))
      temp_k <- as.numeric(as.character(a))

        for(j in 1:n_sim){
    
          ## Everything here is the same as described above, except 
          ## that data is generated according to the 3PL
          temp_data <- data.gen(n = temp_n, k = temp_k, model = "3PL")
                        
          temp_model <- ltm(temp_data ~ z1, IRT.param = TRUE)
          
          l_0 <- temp_model$log.Lik
          
          aggr_data <- score.pattern.aggr(temp_data, temp_n)
          
          df_base <- df.base(k = temp_k)
          
          df_tested <- df.tested(k = temp_k)
          
          chi_base <- chi.base(agg_data = aggr_data, data = temp_data,
                               n = temp_n, k = temp_k)
          
          chi_tested <- chi.tested(l_0 = l_0, agg_data = aggr_data, n = temp_n)
          
          ## And then calculating the TLI and CFI values through our
          ## specialized functions
          tli_values[j] <- TLI.Yang(chi_base = chi_base, df_base = df_base, 
                               chi_tested = chi_tested, df_tested = df_tested)
          
          cfi_values[j] <- CFI.Yang(chi_base = chi_base, df_base = df_base, 
                               chi_tested = chi_tested, df_tested = df_tested)
          
          icfi_values[j] <- exp.obs.FI(model = temp_model, k = temp_k)
        
        }
      
      miss_results <- rbind(miss_results, c(a, b, mean(tli_values, na.rm = TRUE), sd(tli_values, na.rm = TRUE),
                                          mean(cfi_values, na.rm = TRUE), sd(cfi_values, na.rm = TRUE),
                                          mean(icfi_values, na.rm = TRUE), sd(icfi_values, na.rm = TRUE)))

  }
  
}

miss_results <- miss_results[-1 ,]

rownames(miss_results) <- NULL

miss_results
```

## 4. Session Information for Reproducibility

```{r session Info }
sessionInfo()
```

